build_from:
  aarch64: homebridge/homebridge:latest
  amd64: homebridge/homebridge:latest
  armhf: homebridge/homebridge:latest
  armv7: homebridge/homebridge:latest

labels:
  io.hass.version: VERSION
  io.hass.type: addon
  io.hass.arch: aarch64|amd64|armhf|armv7
